apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-list.fullname" . }}
  labels:
    {{- include "todo-list.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret-key: {{ .Values.backend.secretKey | quote }}
